-- Auto-generated from scripts/generate_menu_products_seed.js
-- Target menu_id = 4. Idempotent by (menu_id, lower(name)).

DO $$
DECLARE
    v_menu_id BIGINT := 4;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tbl_menu WHERE menu_id = v_menu_id AND is_deleted = FALSE) THEN
        RAISE EXCEPTION 'Menu % not found or deleted', v_menu_id;
    END IF;
END $$;

WITH seed(name, description, price, currency, sub_slug, sort_order, available, nutrition, tag_slugs, serves_people_min, serves_people_max) AS (
    VALUES
    ('Türk Kahvesi', 'Közde pişmiş klasik Türk kahvesi', 90::numeric, 'TRY', 'sicak_icecekler', 1, TRUE,
     '{"basis":"PER_100ML","energyKj":8,"energyKcal":2,"fat":0.1,"saturatedFat":1.5,"carbohydrate":0.3,"sugars":3,"fibre":1,"protein":0.1,"salt":0}'::jsonb,
     ARRAY['seker_ilavesiz','populer']::text[], 1, 1),
    ('Filtre Kahve', 'Taze çekilmiş filtre kahve', 110::numeric, 'TRY', 'sicak_icecekler', 2, TRUE,
     '{"basis":"PER_100ML","energyKj":8,"energyKcal":2,"fat":0,"saturatedFat":1.5,"carbohydrate":0.2,"sugars":3,"fibre":1,"protein":0.1,"salt":0}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Espresso', 'Tek shot espresso', 85::numeric, 'TRY', 'sicak_icecekler', 3, TRUE,
     '{"basis":"PER_100ML","energyKj":13,"energyKcal":3,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Americano', 'Espresso ve sıcak su', 100::numeric, 'TRY', 'sicak_icecekler', 4, TRUE,
     '{"basis":"PER_100ML","energyKj":8,"energyKcal":2,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Cappuccino', 'Espresso, buharlı süt, süt köpüğü', 130::numeric, 'TRY', 'sicak_icecekler', 5, TRUE,
     '{"basis":"PER_100ML","energyKj":188,"energyKcal":45,"fat":2.5,"saturatedFat":1.5,"carbohydrate":3.5,"sugars":3,"fibre":1,"protein":2.5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Limonata', 'Ev yapımı taze limonata', 95::numeric, 'TRY', 'soguk_icecekler', 6, TRUE,
     '{"basis":"PER_100ML","energyKj":121,"energyKcal":29,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Ice Tea Şeftali', 'Soğuk şeftali çayı', 90::numeric, 'TRY', 'soguk_icecekler', 7, TRUE,
     '{"basis":"PER_100ML","energyKj":117,"energyKcal":28,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Cola', 'Soğuk kola', 70::numeric, 'TRY', 'soguk_icecekler', 8, TRUE,
     '{"basis":"PER_100ML","energyKj":176,"energyKcal":42,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Gazoz', 'Klasik gazoz', 65::numeric, 'TRY', 'soguk_icecekler', 9, TRUE,
     '{"basis":"PER_100ML","energyKj":159,"energyKcal":38,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Ayran', 'Ev yapımı yayık ayran', 55::numeric, 'TRY', 'soguk_icecekler', 10, TRUE,
     '{"basis":"PER_100ML","energyKj":146,"energyKcal":35,"fat":1.5,"saturatedFat":1.5,"carbohydrate":3,"sugars":3,"fibre":1,"protein":2,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz','populer']::text[], 1, 1),
    ('Portakal Suyu', 'Taze sıkılmış portakal', 120::numeric, 'TRY', 'taze_sikilmis_meyve_sulari', 11, TRUE,
     '{"basis":"PER_100ML","energyKj":188,"energyKcal":45,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','seker_ilavesiz']::text[], 1, 1),
    ('Elma Suyu', 'Taze sıkılmış elma', 115::numeric, 'TRY', 'taze_sikilmis_meyve_sulari', 12, TRUE,
     '{"basis":"PER_100ML","energyKj":192,"energyKcal":46,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','seker_ilavesiz']::text[], 1, 1),
    ('Havuç Portakal', 'Havuç ve portakal karışımı', 130::numeric, 'TRY', 'taze_sikilmis_meyve_sulari', 13, TRUE,
     '{"basis":"PER_100ML","energyKj":176,"energyKcal":42,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','yeni']::text[], 1, 1),
    ('Kombucha Zencefil', 'Ev yapımı zencefilli kombucha', 140::numeric, 'TRY', 'fermente_icecekler', 14, TRUE,
     '{"basis":"PER_100ML","energyKj":75,"energyKcal":18,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz','yeni']::text[], 1, 1),
    ('Şalgam Suyu', 'Acılı şalgam', 60::numeric, 'TRY', 'fermente_icecekler', 15, TRUE,
     '{"basis":"PER_100ML","energyKj":50,"energyKcal":12,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili','glutensiz']::text[], 1, 1),
    ('Efes Pilsen', '33cl şişe bira', 150::numeric, 'TRY', 'alkollu_icecekler', 16, TRUE,
     '{"basis":"PER_100ML","energyKj":180,"energyKcal":43,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Kırmızı Şarap Kadeh', 'Ev şarabı kadeh', 220::numeric, 'TRY', 'alkollu_icecekler', 17, TRUE,
     '{"basis":"PER_100ML","energyKj":356,"energyKcal":85,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Rakı Tek', 'Tek duble rakı', 280::numeric, 'TRY', 'alkollu_icecekler', 18, TRUE,
     '{"basis":"PER_100ML","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Sıcak Çikolata', 'Sütlü sıcak çikolata', 125::numeric, 'TRY', 'sutlu_icecekler', 19, TRUE,
     '{"basis":"PER_100ML","energyKj":372,"energyKcal":89,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Latte', 'Espresso ve buharlı süt', 135::numeric, 'TRY', 'sutlu_icecekler', 20, TRUE,
     '{"basis":"PER_100ML","energyKj":201,"energyKcal":48,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Laktozsuz Latte', 'Laktozsuz süt ile latte', 145::numeric, 'TRY', 'sutlu_icecekler', 21, TRUE,
     '{"basis":"PER_100ML","energyKj":176,"energyKcal":42,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz','vejeteryan']::text[], 1, 1),
    ('Çay', 'İnce belli bardak demlik çay', 40::numeric, 'TRY', 'caylar', 22, TRUE,
     '{"basis":"PER_100ML","energyKj":4,"energyKcal":1,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz','populer']::text[], 1, 1),
    ('Adaçayı', 'Taze adaçayı', 70::numeric, 'TRY', 'caylar', 23, TRUE,
     '{"basis":"PER_100ML","energyKj":4,"energyKcal":1,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Ihlamur', 'Ballı ıhlamur', 75::numeric, 'TRY', 'caylar', 24, TRUE,
     '{"basis":"PER_100ML","energyKj":75,"energyKcal":18,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Çilek Smoothie', 'Çilek, muz, yoğurt', 160::numeric, 'TRY', 'smoothie_ve_shake', 25, TRUE,
     '{"basis":"PER_100ML","energyKj":301,"energyKcal":72,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','yeni']::text[], 1, 1),
    ('Protein Shake', 'Muzlu whey protein shake', 180::numeric, 'TRY', 'smoothie_ve_shake', 26, TRUE,
     '{"basis":"PER_100ML","energyKj":397,"energyKcal":95,"fat":2,"saturatedFat":1.5,"carbohydrate":8,"sugars":3,"fibre":1,"protein":12,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Yeşil Detoks', 'Ispanak, elma, limon smoothie', 170::numeric, 'TRY', 'smoothie_ve_shake', 27, TRUE,
     '{"basis":"PER_100ML","energyKj":230,"energyKcal":55,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Ezogelin Çorbası', 'Nane ve pul biberli', 130::numeric, 'TRY', 'et_suyu_corbalar', 28, TRUE,
     '{"basis":"PER_100G","energyKj":310,"energyKcal":74,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','populer']::text[], 1, 1),
    ('İşkembe Çorbası', 'Sarımsaklı işkembe', 180::numeric, 'TRY', 'et_suyu_corbalar', 29, TRUE,
     '{"basis":"PER_100G","energyKj":397,"energyKcal":95,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Tavuk Suyu Çorba', 'Şehriyeli tavuk suyu', 125::numeric, 'TRY', 'et_suyu_corbalar', 30, TRUE,
     '{"basis":"PER_100G","energyKj":201,"energyKcal":48,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Mercimek Çorbası', 'Tereyağlı mercimek', 130::numeric, 'TRY', 'kremali_corbalar', 31, TRUE,
     '{"basis":"PER_100G","energyKj":280,"energyKcal":67,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz','populer']::text[], 1, 1),
    ('Mantar Çorbası', 'Kremalı mantar', 145::numeric, 'TRY', 'kremali_corbalar', 32, TRUE,
     '{"basis":"PER_100G","energyKj":343,"energyKcal":82,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Brokoli Çorbası', 'Kremalı brokoli', 140::numeric, 'TRY', 'kremali_corbalar', 33, TRUE,
     '{"basis":"PER_100G","energyKj":293,"energyKcal":70,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Balık Çorbası', 'Mevsim balığı ile', 190::numeric, 'TRY', 'deniz_urunu_corbalar', 34, TRUE,
     '{"basis":"PER_100G","energyKj":326,"energyKcal":78,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz']::text[], 1, 1),
    ('Karides Çorbası', 'Krema ve karides', 210::numeric, 'TRY', 'deniz_urunu_corbalar', 35, TRUE,
     '{"basis":"PER_100G","energyKj":385,"energyKcal":92,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Domates Çorbası', 'Fesleğenli domates', 120::numeric, 'TRY', 'sebze_corbalar', 36, TRUE,
     '{"basis":"PER_100G","energyKj":176,"energyKcal":42,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Tarhana Çorbası', 'Ev yapımı tarhana', 115::numeric, 'TRY', 'sebze_corbalar', 37, TRUE,
     '{"basis":"PER_100G","energyKj":230,"energyKcal":55,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Zeytin Tabağı', 'Karışık zeytin', 110::numeric, 'TRY', 'soguk_baslangiclar', 38, TRUE,
     '{"basis":"PER_100G","energyKj":607,"energyKcal":145,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Peynir Tabağı', 'Üç çeşit peynir', 180::numeric, 'TRY', 'soguk_baslangiclar', 39, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Antipasto Mini', 'Salam, zeytin, grissini', 200::numeric, 'TRY', 'soguk_baslangiclar', 40, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['yeni']::text[], 1, 1),
    ('Paçanga Böreği', 'Pastırmalı paçanga', 160::numeric, 'TRY', 'sicak_baslangiclar', 41, TRUE,
     '{"basis":"PER_100G","energyKj":1297,"energyKcal":310,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Kalamar Tava', 'Çıtır kalamar', 240::numeric, 'TRY', 'sicak_baslangiclar', 42, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Mücver', 'Kabaklı mücver', 140::numeric, 'TRY', 'sicak_baslangiclar', 43, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Çoban Salata', 'Domates, salatalık, soğan', 140::numeric, 'TRY', 'salatalar', 44, TRUE,
     '{"basis":"PER_100G","energyKj":209,"energyKcal":50,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','populer']::text[], 1, 1),
    ('Sezar Salata', 'Tavuklu Sezar', 220::numeric, 'TRY', 'salatalar', 45, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Akdeniz Salata', 'Roka, zeytin, peynir', 180::numeric, 'TRY', 'salatalar', 46, TRUE,
     '{"basis":"PER_100G","energyKj":502,"energyKcal":120,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Quinoa Salata', 'Quinoa, avokado, nar', 210::numeric, 'TRY', 'salatalar', 47, TRUE,
     '{"basis":"PER_100G","energyKj":607,"energyKcal":145,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','yeni']::text[], 1, 1),
    ('Humus', 'Tahinli nohut humusu', 120::numeric, 'TRY', 'soguk_mezeler', 48, TRUE,
     '{"basis":"PER_100G","energyKj":690,"energyKcal":165,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','populer']::text[], 1, 1),
    ('Haydari', 'Süzme yoğurtlu haydari', 110::numeric, 'TRY', 'soguk_mezeler', 49, TRUE,
     '{"basis":"PER_100G","energyKj":397,"energyKcal":95,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Acılı Ezme', 'Acılı domates ezmesi', 100::numeric, 'TRY', 'soguk_mezeler', 50, TRUE,
     '{"basis":"PER_100G","energyKj":293,"energyKcal":70,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili','glutensiz']::text[], 1, 1),
    ('Atom', 'Acılı atom meze', 115::numeric, 'TRY', 'soguk_mezeler', 51, TRUE,
     '{"basis":"PER_100G","energyKj":460,"energyKcal":110,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','acili']::text[], 1, 1),
    ('Sigara Böreği', 'Peynirli çıtır börek', 150::numeric, 'TRY', 'sicak_mezeler', 52, TRUE,
     '{"basis":"PER_100G","energyKj":1247,"energyKcal":298,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('İçli Köfte', '2 adet içli köfte', 170::numeric, 'TRY', 'sicak_mezeler', 53, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Arnavut Ciğeri', 'Kızartma ciğer', 190::numeric, 'TRY', 'sicak_mezeler', 54, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Zeytinyağlı Yaprak Sarma', '8 adet sarma', 160::numeric, 'TRY', 'zeytinyaglilar', 55, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Zeytinyağlı Enginar', 'Bakla ve havuç ile', 175::numeric, 'TRY', 'zeytinyaglilar', 56, TRUE,
     '{"basis":"PER_100G","energyKj":397,"energyKcal":95,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('İmam Bayıldı', 'Zeytinyağlı patlıcan', 165::numeric, 'TRY', 'zeytinyaglilar', 57, TRUE,
     '{"basis":"PER_100G","energyKj":586,"energyKcal":140,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Izgara Köfte', 'Dana kıyma köfte, pilav', 320::numeric, 'TRY', 'et_yemekleri', 58, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','populer']::text[], 1, 1),
    ('Kuzu Tandır', 'Fırın kuzu tandır', 480::numeric, 'TRY', 'et_yemekleri', 59, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel','glutensiz']::text[], 1, 1),
    ('Dana Rosto', 'Sebzeli dana rosto', 420::numeric, 'TRY', 'et_yemekleri', 60, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Hünkar Beğendi', 'Kuzu ve beğendi', 390::numeric, 'TRY', 'et_yemekleri', 61, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Tavuk Şiş', 'Marine tavuk şiş', 280::numeric, 'TRY', 'tavuk_yemekleri', 62, TRUE,
     '{"basis":"PER_100G","energyKj":699,"energyKcal":167,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','populer']::text[], 1, 1),
    ('Tavuk Sote', 'Sebzeli tavuk sote', 260::numeric, 'TRY', 'tavuk_yemekleri', 63, TRUE,
     '{"basis":"PER_100G","energyKj":649,"energyKcal":155,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Krema Soslu Tavuk', 'Mantarlı krema sos', 290::numeric, 'TRY', 'tavuk_yemekleri', 64, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Sebzeli Güveç', 'Fırın mevsim sebzeleri', 240::numeric, 'TRY', 'vejeteryan_ana_yemekler', 65, TRUE,
     '{"basis":"PER_100G","energyKj":418,"energyKcal":100,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Mantı', 'Yoğurtlu ev mantısı', 250::numeric, 'TRY', 'vejeteryan_ana_yemekler', 66, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Patlıcan Musakka', 'Fırın musakka', 230::numeric, 'TRY', 'vejeteryan_ana_yemekler', 67, TRUE,
     '{"basis":"PER_100G","energyKj":690,"energyKcal":165,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Mercimek Köftesi', 'Baharatlı mercimek köftesi', 180::numeric, 'TRY', 'vegan_ana_yemekler', 68, TRUE,
     '{"basis":"PER_100G","energyKj":778,"energyKcal":186,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili']::text[], 1, 1),
    ('Nohut Yemeği', 'Zeytinyağlı nohut', 170::numeric, 'TRY', 'vegan_ana_yemekler', 69, TRUE,
     '{"basis":"PER_100G","energyKj":586,"energyKcal":140,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Falafel Tabağı', 'Humus ve salata ile', 200::numeric, 'TRY', 'vegan_ana_yemekler', 70, TRUE,
     '{"basis":"PER_100G","energyKj":816,"energyKcal":195,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','yeni']::text[], 1, 1),
    ('Spaghetti Bolognese', 'Kıymalı bolognese', 260::numeric, 'TRY', 'makarna_cesitleri', 71, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Penne Arrabbiata', 'Acılı domates sos', 230::numeric, 'TRY', 'makarna_cesitleri', 72, TRUE,
     '{"basis":"PER_100G","energyKj":732,"energyKcal":175,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili']::text[], 1, 1),
    ('Fettuccine Alfredo', 'Krema ve parmesan', 270::numeric, 'TRY', 'makarna_cesitleri', 73, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Tereyağlı Pilav', 'Pirinç pilavı', 90::numeric, 'TRY', 'pilav_cesitleri', 74, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Bulgur Pilavı', 'Domatesli bulgur', 95::numeric, 'TRY', 'pilav_cesitleri', 75, TRUE,
     '{"basis":"PER_100G","energyKj":607,"energyKcal":145,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('İç Pilav', 'Fıstıklı iç pilav', 120::numeric, 'TRY', 'pilav_cesitleri', 76, TRUE,
     '{"basis":"PER_100G","energyKj":732,"energyKcal":175,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Kuzu Güveç', 'Fırın kuzu güveç', 410::numeric, 'TRY', 'guvec_yemekleri', 77, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','sef_ozel']::text[], 1, 1),
    ('Türlü Güveç', 'Sebze türlü', 220::numeric, 'TRY', 'guvec_yemekleri', 78, TRUE,
     '{"basis":"PER_100G","energyKj":397,"energyKcal":95,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Mantarlı Güveç', 'Kaşarlı mantar güveç', 240::numeric, 'TRY', 'guvec_yemekleri', 79, TRUE,
     '{"basis":"PER_100G","energyKj":544,"energyKcal":130,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Kıymalı Pide', 'Klasik kıymalı pide', 260::numeric, 'TRY', 'kiyma_pideler', 80, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','populer']::text[], 1, 1),
    ('Kuşbaşılı Pide', 'Kuşbaşı etli pide', 310::numeric, 'TRY', 'kiyma_pideler', 81, TRUE,
     '{"basis":"PER_100G","energyKj":1130,"energyKcal":270,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Kaşarlı Pide', 'Bol kaşarlı pide', 240::numeric, 'TRY', 'peynirli_pideler', 82, TRUE,
     '{"basis":"PER_100G","energyKj":1109,"energyKcal":265,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Üç Peynirli Pide', 'Kaşar, lor, beyaz peynir', 270::numeric, 'TRY', 'peynirli_pideler', 83, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Karışık Pide', 'Kıyma ve kaşar', 290::numeric, 'TRY', 'karisik_pideler', 84, TRUE,
     '{"basis":"PER_100G","energyKj":1151,"energyKcal":275,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Pastırmalı Pide', 'Pastırma ve yumurta', 320::numeric, 'TRY', 'karisik_pideler', 85, TRUE,
     '{"basis":"PER_100G","energyKj":1234,"energyKcal":295,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Lahmacun', 'İnce hamur lahmacun', 120::numeric, 'TRY', 'lahmacun', 86, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Fındık Lahmacun', 'Küçük boy 3 adet', 150::numeric, 'TRY', 'lahmacun', 87, TRUE,
     '{"basis":"PER_100G","energyKj":837,"energyKcal":200,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Margarita Pizza', 'Domates, mozzarella, fesleğen', 290::numeric, 'TRY', 'klasik_pizzalar', 88, TRUE,
     '{"basis":"PER_100G","energyKj":1117,"energyKcal":267,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Pepperoni Pizza', 'Pepperoni ve mozzarella', 330::numeric, 'TRY', 'klasik_pizzalar', 89, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Karışık Pizza', 'Sucuk, mantar, biber', 340::numeric, 'TRY', 'klasik_pizzalar', 90, TRUE,
     '{"basis":"PER_100G","energyKj":1192,"energyKcal":285,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Trüf Mantarlı Pizza', 'Trüf yağı ve mantar', 420::numeric, 'TRY', 'ozel_pizzalar', 91, TRUE,
     '{"basis":"PER_100G","energyKj":1255,"energyKcal":300,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','sef_ozel']::text[], 1, 1),
    ('BBQ Tavuk Pizza', 'Barbekü soslu tavuk', 360::numeric, 'TRY', 'ozel_pizzalar', 92, TRUE,
     '{"basis":"PER_100G","energyKj":1151,"energyKcal":275,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['yeni']::text[], 1, 1),
    ('Kruvasan Pizza Klasik', 'İnce kruvasan hamur', 310::numeric, 'TRY', 'ince_kruvasan_pizzalar', 93, TRUE,
     '{"basis":"PER_100G","energyKj":1067,"energyKcal":255,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Kruvasan Pizza Sucuklu', 'Sucuk ve kaşar', 330::numeric, 'TRY', 'ince_kruvasan_pizzalar', 94, TRUE,
     '{"basis":"PER_100G","energyKj":1130,"energyKcal":270,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Tavuklu Sandviç', 'Izgara tavuk sandviç', 200::numeric, 'TRY', 'klasik_sandvicler', 95, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Ton Balıklı Sandviç', 'Ton ve yeşillik', 190::numeric, 'TRY', 'klasik_sandvicler', 96, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Sebzeli Sandviç', 'Izgara sebze', 170::numeric, 'TRY', 'klasik_sandvicler', 97, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Kaşarlı Tost', 'Klasik kaşar tost', 120::numeric, 'TRY', 'tostlar', 98, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Sucuklu Tost', 'Sucuk ve kaşar', 150::numeric, 'TRY', 'tostlar', 99, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Ayvalık Tostu', 'Bol malzemeli', 180::numeric, 'TRY', 'tostlar', 100, TRUE,
     '{"basis":"PER_100G","energyKj":1464,"energyKcal":350,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Tavuk Wrap', 'Izgara tavuk wrap', 210::numeric, 'TRY', 'wraplar', 101, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Falafel Wrap', 'Falafel ve humus', 190::numeric, 'TRY', 'wraplar', 102, TRUE,
     '{"basis":"PER_100G","energyKj":900,"energyKcal":215,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Cheeseburger', 'Dana köfte, cheddar', 310::numeric, 'TRY', 'klasik_burgerler', 103, TRUE,
     '{"basis":"PER_100G","energyKj":1180,"energyKcal":282,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Classic Burger', 'Dana köfte, turşu, sos', 290::numeric, 'TRY', 'klasik_burgerler', 104, TRUE,
     '{"basis":"PER_100G","energyKj":1109,"energyKcal":265,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Double Burger', 'Çift köfte', 380::numeric, 'TRY', 'klasik_burgerler', 105, TRUE,
     '{"basis":"PER_100G","energyKj":1423,"energyKcal":340,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Truffle Burger', 'Trüf mayonez ve cheddar', 420::numeric, 'TRY', 'ozel_burgerler', 106, TRUE,
     '{"basis":"PER_100G","energyKj":1297,"energyKcal":310,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('BBQ Bacon Burger', 'Barbekü ve pastırma', 390::numeric, 'TRY', 'ozel_burgerler', 107, TRUE,
     '{"basis":"PER_100G","energyKj":1381,"energyKcal":330,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['yeni']::text[], 1, 1),
    ('Mantar Burger', 'Portobello mantar', 270::numeric, 'TRY', 'vejeteryan_burgerler', 108, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Falafel Burger', 'Falafel köfte', 250::numeric, 'TRY', 'vejeteryan_burgerler', 109, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Sütlaç', 'Fırın sütlaç', 140::numeric, 'TRY', 'sutlu_tatlilar', 110, TRUE,
     '{"basis":"PER_100G","energyKj":540,"energyKcal":129,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz','populer']::text[], 1, 1),
    ('Kazandibi', 'Karamelize kazandibi', 150::numeric, 'TRY', 'sutlu_tatlilar', 111, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Muhallebi', 'Gül suları muhallebi', 130::numeric, 'TRY', 'sutlu_tatlilar', 112, TRUE,
     '{"basis":"PER_100G","energyKj":502,"energyKcal":120,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Baklava', 'Antep fıstıklı baklava', 180::numeric, 'TRY', 'serbetli_tatlilar', 113, TRUE,
     '{"basis":"PER_100G","energyKj":1791,"energyKcal":428,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Künefe', 'Sıcak künefe', 200::numeric, 'TRY', 'serbetli_tatlilar', 114, TRUE,
     '{"basis":"PER_100G","energyKj":1590,"energyKcal":380,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Şöbiyet', 'Kaymaklı şöbiyet', 190::numeric, 'TRY', 'serbetli_tatlilar', 115, TRUE,
     '{"basis":"PER_100G","energyKj":1715,"energyKcal":410,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Tulumba', 'Şerbetli tulumba', 120::numeric, 'TRY', 'hamur_isi_tatlilar', 116, TRUE,
     '{"basis":"PER_100G","energyKj":1464,"energyKcal":350,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Lokma', 'Sıcak lokma', 110::numeric, 'TRY', 'hamur_isi_tatlilar', 117, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Meyve Salatası', 'Mevsim meyveleri', 130::numeric, 'TRY', 'meyveli_tatlilar', 118, TRUE,
     '{"basis":"PER_100G","energyKj":230,"energyKcal":55,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz','seker_ilavesiz']::text[], 1, 1),
    ('Çilekli Magnolia', 'Çilek magnolia', 160::numeric, 'TRY', 'meyveli_tatlilar', 119, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Dondurma 2 Top', 'İki top dondurma', 100::numeric, 'TRY', 'dondurmalar', 120, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz','populer']::text[], 1, 1),
    ('Maraş Dondurma', 'Geleneksel Maraş dondurması', 140::numeric, 'TRY', 'dondurmalar', 121, TRUE,
     '{"basis":"PER_100G","energyKj":837,"energyKcal":200,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Çikolata Top', 'Tek top bitter çikolata dondurma', 70::numeric, 'TRY', 'dondurmalar', 122, TRUE,
     '{"basis":"PER_100G","energyKj":795,"energyKcal":190,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Magnolia', 'Bisküvili soğuk magnolia', 160::numeric, 'TRY', 'soguk_tatlilar', 123, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Tiramisu', 'Klasik soğuk tiramisu', 180::numeric, 'TRY', 'soguk_tatlilar', 124, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Panna Cotta', 'Vanilyalı panna cotta', 150::numeric, 'TRY', 'soguk_tatlilar', 125, TRUE,
     '{"basis":"PER_100G","energyKj":795,"energyKcal":190,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Çikolatalı Sufle', 'Sıcak çikolata suflesi', 190::numeric, 'TRY', 'cikolatali_tatlilar', 126, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','sef_ozel']::text[], 1, 1),
    ('Brownie', 'Cevizli brownie', 150::numeric, 'TRY', 'cikolatali_tatlilar', 127, TRUE,
     '{"basis":"PER_100G","energyKj":1590,"energyKcal":380,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Profiterol', 'Çikolata soslu profiterol', 160::numeric, 'TRY', 'cikolatali_tatlilar', 128, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Çikolatalı Pasta Dilim', 'Yoğun çikolata pasta', 170::numeric, 'TRY', 'cikolatali_tatlilar', 129, TRUE,
     '{"basis":"PER_100G","energyKj":1423,"energyKcal":340,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Cheesecake', 'Frambuazlı cheesecake', 180::numeric, 'TRY', 'pasta_cesitleri', 130, TRUE,
     '{"basis":"PER_100G","energyKj":1297,"energyKcal":310,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Orman Meyveli Pasta', 'Kremalı orman meyveli dilim', 175::numeric, 'TRY', 'pasta_cesitleri', 131, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Havuçlu Kek', 'Cevizli havuç kek', 140::numeric, 'TRY', 'kek_cesitleri', 132, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Mozaik Kek', 'Bitter çikolatalı mozaik', 130::numeric, 'TRY', 'kek_cesitleri', 133, TRUE,
     '{"basis":"PER_100G","energyKj":1255,"energyKcal":300,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Limonlu Kek', 'Taze limonlu kek dilimi', 135::numeric, 'TRY', 'kek_cesitleri', 134, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Serpme Kahvaltı (2 Kişilik)', 'Zengin serpme kahvaltı', 650::numeric, 'TRY', 'serpme_kahvalti', 135, TRUE,
     '{"basis":"PER_100G","energyKj":1883,"energyKcal":450,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 2, 2),
    ('Tek Kişilik Kahvaltı', 'Standart kahvaltı tabağı', 280::numeric, 'TRY', 'serpme_kahvalti', 136, TRUE,
     '{"basis":"PER_100G","energyKj":1590,"energyKcal":380,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Menemen', 'Domatesli menemen', 160::numeric, 'TRY', 'omlet_ve_yumurta_cesitleri', 137, TRUE,
     '{"basis":"PER_100G","energyKj":519,"energyKcal":124,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz','populer']::text[], 1, 1),
    ('Kaşarlı Omlet', 'Üç yumurta omlet', 150::numeric, 'TRY', 'omlet_ve_yumurta_cesitleri', 138, TRUE,
     '{"basis":"PER_100G","energyKj":795,"energyKcal":190,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Sahanda Yumurta', 'Tereyağlı sahanda', 120::numeric, 'TRY', 'omlet_ve_yumurta_cesitleri', 139, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Bal Kaymak', 'Petek bal ve kaymak', 180::numeric, 'TRY', 'kahvaltilik_tatlilar', 140, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Reçel Tabağı', 'Üç çeşit reçel', 90::numeric, 'TRY', 'kahvaltilik_tatlilar', 141, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','vegan']::text[], 1, 1),
    ('Peynirli Gözleme', 'İnce hamur peynirli', 140::numeric, 'TRY', 'gozleme', 142, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','populer']::text[], 1, 1),
    ('Patatesli Gözleme', 'Baharatlı patates', 130::numeric, 'TRY', 'gozleme', 143, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Ispanaklı Gözleme', 'Ispanak ve peynir', 145::numeric, 'TRY', 'gozleme', 144, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Tandır Ekmeği', 'Sıcak tandır', 40::numeric, 'TRY', 'ekmek_ve_hamur_isleri', 145, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Poğaça', 'Peynirli poğaça', 50::numeric, 'TRY', 'ekmek_ve_hamur_isleri', 146, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Sarımsaklı Mayonez', 'Ekstra sos', 25::numeric, 'TRY', 'soslar', 147, TRUE,
     '{"basis":"PER_100G","energyKj":1883,"energyKcal":450,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Acı Sos', 'Ev yapımı acı sos', 25::numeric, 'TRY', 'soslar', 148, TRUE,
     '{"basis":"PER_100G","energyKj":167,"energyKcal":40,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili','glutensiz']::text[], 1, 1),
    ('Pilav Porsiyon', 'Yan pilav', 70::numeric, 'TRY', 'garniturler', 149, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Izgara Sebze', 'Mevsim ızgara sebze', 90::numeric, 'TRY', 'garniturler', 150, TRUE,
     '{"basis":"PER_100G","energyKj":251,"energyKcal":60,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Et Dürüm', 'Lavaşta et döner', 280::numeric, 'TRY', 'et_durum', 151, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Et Durum Extra', 'Bol et dürüm', 340::numeric, 'TRY', 'et_durum', 152, TRUE,
     '{"basis":"PER_100G","energyKj":1297,"energyKcal":310,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Tavuk Dürüm', 'Lavaşta tavuk döner', 240::numeric, 'TRY', 'tavuk_durum', 153, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Tavuk Durum Acılı', 'Acılı tavuk dürüm', 250::numeric, 'TRY', 'tavuk_durum', 154, TRUE,
     '{"basis":"PER_100G","energyKj":983,"energyKcal":235,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Et Döner Porsiyon', 'Pilav üstü et döner', 320::numeric, 'TRY', 'doner_porsiyon', 155, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Tavuk Döner Porsiyon', 'Pilav üstü tavuk', 280::numeric, 'TRY', 'doner_porsiyon', 156, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('İskender', 'Tereyağlı iskender', 380::numeric, 'TRY', 'iskender', 157, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer','sef_ozel']::text[], 1, 1),
    ('Tavuk İskender', 'Tavuklu iskender', 340::numeric, 'TRY', 'iskender', 158, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Antrikot', '300g antrikot', 620::numeric, 'TRY', 'kirmizi_et_izgara', 159, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','sef_ozel']::text[], 1, 1),
    ('Bonfile', '250g bonfile', 680::numeric, 'TRY', 'kirmizi_et_izgara', 160, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Pirzola', 'Kuzu pirzola', 590::numeric, 'TRY', 'kirmizi_et_izgara', 161, TRUE,
     '{"basis":"PER_100G","energyKj":1130,"energyKcal":270,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Izgara Tavuk Pirzola', 'Baharatlı tavuk', 300::numeric, 'TRY', 'tavuk_izgara', 162, TRUE,
     '{"basis":"PER_100G","energyKj":690,"energyKcal":165,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Kanat Izgara', 'Acılı kanat', 260::numeric, 'TRY', 'tavuk_izgara', 163, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Karışık Izgara', 'Köfte, şiş, kanat', 520::numeric, 'TRY', 'karisik_izgara', 164, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer','glutensiz']::text[], 1, 1),
    ('Special Karışık', 'Bonfile dahil karışık', 720::numeric, 'TRY', 'karisik_izgara', 165, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Levrek Izgara', 'Bütün levrek', 480::numeric, 'TRY', 'balik_cesitleri', 166, TRUE,
     '{"basis":"PER_100G","energyKj":586,"energyKcal":140,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','laktozsuz']::text[], 1, 1),
    ('Çipura Izgara', 'Bütün çipura', 460::numeric, 'TRY', 'balik_cesitleri', 167, TRUE,
     '{"basis":"PER_100G","energyKj":607,"energyKcal":145,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','laktozsuz']::text[], 1, 1),
    ('Somon Izgara', 'Norveç somon', 520::numeric, 'TRY', 'balik_cesitleri', 168, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Karides Güveç', 'Kaşarlı karides', 420::numeric, 'TRY', 'kabuklu_deniz_urunleri', 169, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel']::text[], 1, 1),
    ('Midye Dolma', '10 adet midye', 200::numeric, 'TRY', 'kabuklu_deniz_urunleri', 170, TRUE,
     '{"basis":"PER_100G","energyKj":502,"energyKcal":120,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Ahtapot Salata', 'Zeytinyağlı ahtapot', 320::numeric, 'TRY', 'meze_tarzi_deniz_urunleri', 171, TRUE,
     '{"basis":"PER_100G","energyKj":460,"energyKcal":110,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz','glutensiz']::text[], 1, 1),
    ('Füme Somon', 'Kapari ve limon', 280::numeric, 'TRY', 'meze_tarzi_deniz_urunleri', 172, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz','glutensiz']::text[], 1, 1),
    ('Patates Kızartması', 'Klasik patates', 110::numeric, 'TRY', 'patates_kizartmasi_cesitleri', 173, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','populer']::text[], 1, 1),
    ('Baharatlı Patates', 'Çeşnili patates', 130::numeric, 'TRY', 'patates_kizartmasi_cesitleri', 174, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','acili']::text[], 1, 1),
    ('Truffle Patates', 'Trüf yağlı', 180::numeric, 'TRY', 'patates_kizartmasi_cesitleri', 175, TRUE,
     '{"basis":"PER_100G","energyKj":1255,"energyKcal":300,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','sef_ozel']::text[], 1, 1),
    ('Soğan Halkası', 'Çıtır soğan halkası', 120::numeric, 'TRY', 'kizartmalar', 176, TRUE,
     '{"basis":"PER_100G","energyKj":1297,"energyKcal":310,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Mozzarella Stick', '6 adet', 160::numeric, 'TRY', 'kizartmalar', 177, TRUE,
     '{"basis":"PER_100G","energyKj":1423,"energyKcal":340,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Nachos', 'Cheddar ve salsa', 190::numeric, 'TRY', 'cips_ve_nachos', 178, TRUE,
     '{"basis":"PER_100G","energyKj":1339,"energyKcal":320,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','acili']::text[], 1, 1),
    ('Cips Tabağı', 'Karışık cips', 100::numeric, 'TRY', 'cips_ve_nachos', 179, TRUE,
     '{"basis":"PER_100G","energyKj":1674,"energyKcal":400,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Mojito', 'Nane, lime, rom', 280::numeric, 'TRY', 'alkollu_kokteyller', 180, TRUE,
     '{"basis":"PER_100ML","energyKj":397,"energyKcal":95,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Margarita', 'Tekila, triple sec', 290::numeric, 'TRY', 'alkollu_kokteyller', 181, TRUE,
     '{"basis":"PER_100ML","energyKj":460,"energyKcal":110,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Gin Tonic', 'Gin ve tonic', 270::numeric, 'TRY', 'alkollu_kokteyller', 182, TRUE,
     '{"basis":"PER_100ML","energyKj":335,"energyKcal":80,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Virgin Mojito', 'Alkolsüz mojito', 160::numeric, 'TRY', 'alkolsuz_kokteyller', 183, TRUE,
     '{"basis":"PER_100ML","energyKj":146,"energyKcal":35,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','seker_ilavesiz']::text[], 1, 1),
    ('Fruit Punch', 'Karışık meyve punch', 150::numeric, 'TRY', 'alkolsuz_kokteyller', 184, TRUE,
     '{"basis":"PER_100ML","energyKj":201,"energyKcal":48,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Pad Thai', 'Karidesli pad thai', 320::numeric, 'TRY', 'noodle_cesitleri', 185, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','yeni']::text[], 1, 1),
    ('Sebzeli Noodle', 'Wok sebze noodle', 250::numeric, 'TRY', 'noodle_cesitleri', 186, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('California Roll', '8 parça', 260::numeric, 'TRY', 'sushi', 187, TRUE,
     '{"basis":"PER_100G","energyKj":649,"energyKcal":155,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz','populer']::text[], 1, 1),
    ('Somom Roll', '8 parça somon', 290::numeric, 'TRY', 'sushi', 188, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['laktozsuz']::text[], 1, 1),
    ('Vegan Roll', 'Avokado ve salatalık', 230::numeric, 'TRY', 'sushi', 189, TRUE,
     '{"basis":"PER_100G","energyKj":586,"energyKcal":140,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','laktozsuz']::text[], 1, 1),
    ('Tavuk Wok', 'Sebzeli tavuk wok', 280::numeric, 'TRY', 'wok_yemekleri', 190, TRUE,
     '{"basis":"PER_100G","energyKj":795,"energyKcal":190,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Dana Wok', 'Biberli dana wok', 340::numeric, 'TRY', 'wok_yemekleri', 191, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','sef_ozel']::text[], 1, 1),
    ('Shoyu Ramen', 'Soya bazlı ramen', 300::numeric, 'TRY', 'ramen', 192, TRUE,
     '{"basis":"PER_100G","energyKj":920,"energyKcal":220,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['yeni']::text[], 1, 1),
    ('Spicy Miso Ramen', 'Acılı miso ramen', 320::numeric, 'TRY', 'ramen', 193, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','yeni']::text[], 1, 1),
    ('Çocuk Köfte', 'Küçük porsiyon köfte', 180::numeric, 'TRY', 'cocuk_ana_yemekleri', 194, TRUE,
     '{"basis":"PER_100G","energyKj":837,"energyKcal":200,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Çocuk Nugget', 'Patates ile nugget', 170::numeric, 'TRY', 'cocuk_ana_yemekleri', 195, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY[]::text[], 1, 1),
    ('Çocuk Makarna', 'Tereyağlı makarna', 150::numeric, 'TRY', 'cocuk_ana_yemekleri', 196, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Çocuk Dondurma', 'Tek top dondurma', 70::numeric, 'TRY', 'cocuk_tatlilari', 197, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Mini Pancake', 'Çikolata soslu', 110::numeric, 'TRY', 'cocuk_tatlilari', 198, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Çocuk Süt', 'Sıcak/soğuk süt', 45::numeric, 'TRY', 'cocuk_icecekleri', 199, TRUE,
     '{"basis":"PER_100ML","energyKj":251,"energyKcal":60,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Meyveli Soda', 'Alkolsüz meyve soda', 55::numeric, 'TRY', 'cocuk_icecekleri', 200, TRUE,
     '{"basis":"PER_100ML","energyKj":167,"energyKcal":40,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Mantarlı Risotto', 'Parmesanlı risotto', 280::numeric, 'TRY', 'risotto', 201, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Deniz Mahsullü Risotto', 'Karides ve midye', 360::numeric, 'TRY', 'risotto', 202, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['sef_ozel','glutensiz']::text[], 1, 1),
    ('Lazanya', 'Kıymalı lazanya', 290::numeric, 'TRY', 'lazanya_ve_firin_makarna', 203, TRUE,
     '{"basis":"PER_100G","energyKj":1046,"energyKcal":250,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['populer']::text[], 1, 1),
    ('Fırın Makarna', 'Beşamel soslu', 250::numeric, 'TRY', 'lazanya_ve_firin_makarna', 204, TRUE,
     '{"basis":"PER_100G","energyKj":1004,"energyKcal":240,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Bruschetta', 'Domatesli bruschetta', 160::numeric, 'TRY', 'antipasti', 205, TRUE,
     '{"basis":"PER_100G","energyKj":753,"energyKcal":180,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan']::text[], 1, 1),
    ('Caprese', 'Mozzarella ve domates', 190::numeric, 'TRY', 'antipasti', 206, TRUE,
     '{"basis":"PER_100G","energyKj":669,"energyKcal":160,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1),
    ('Et Taco (3 Adet)', 'Baharatlı et taco', 280::numeric, 'TRY', 'taco', 207, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','yeni']::text[], 1, 1),
    ('Tavuk Taco (3 Adet)', 'Izgara tavuk taco', 260::numeric, 'TRY', 'taco', 208, TRUE,
     '{"basis":"PER_100G","energyKj":879,"energyKcal":210,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili']::text[], 1, 1),
    ('Burrito', 'Etli burrito', 300::numeric, 'TRY', 'burrito_ve_quesadilla', 209, TRUE,
     '{"basis":"PER_100G","energyKj":1172,"energyKcal":280,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['acili','populer']::text[], 1, 1),
    ('Quesadilla', 'Peynirli quesadilla', 240::numeric, 'TRY', 'burrito_ve_quesadilla', 210, TRUE,
     '{"basis":"PER_100G","energyKj":1088,"energyKcal":260,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan']::text[], 1, 1),
    ('Tavuk Fajita', 'Biberli tavuk fajita', 320::numeric, 'TRY', 'fajita', 211, TRUE,
     '{"basis":"PER_100G","energyKj":837,"energyKcal":200,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','acili']::text[], 1, 1),
    ('Et Fajita', 'Dana fajita', 360::numeric, 'TRY', 'fajita', 212, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','acili']::text[], 1, 1),
    ('Ribeye Steak', '350g ribeye', 890::numeric, 'TRY', 'steak_cesitleri', 213, TRUE,
     '{"basis":"PER_100G","energyKj":1213,"energyKcal":290,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','sef_ozel']::text[], 1, 1),
    ('T-Bone Steak', '450g T-bone', 980::numeric, 'TRY', 'steak_cesitleri', 214, TRUE,
     '{"basis":"PER_100G","energyKj":1255,"energyKcal":300,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz']::text[], 1, 1),
    ('Filet Mignon', '220g filet', 920::numeric, 'TRY', 'steak_cesitleri', 215, TRUE,
     '{"basis":"PER_100G","energyKj":962,"energyKcal":230,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['glutensiz','populer']::text[], 1, 1),
    ('Fırın Patates', 'Steak yanı', 90::numeric, 'TRY', 'steak_yanlari', 216, TRUE,
     '{"basis":"PER_100G","energyKj":628,"energyKcal":150,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vegan','glutensiz']::text[], 1, 1),
    ('Izgara Mantar', 'Tereyağlı mantar', 100::numeric, 'TRY', 'steak_yanlari', 217, TRUE,
     '{"basis":"PER_100G","energyKj":377,"energyKcal":90,"fat":5,"saturatedFat":1.5,"carbohydrate":10,"sugars":3,"fibre":1,"protein":5,"salt":0.5}'::jsonb,
     ARRAY['vejeteryan','glutensiz']::text[], 1, 1)
),
ins AS (
    INSERT INTO tbl_menu_products (
        menu_id, name, description, price, currency, sub_category_id,
        sort_order, available, nutrition, serves_people_min, serves_people_max,
        created_at, updated_at, is_deleted
    )
    SELECT
        4,
        s.name,
        s.description,
        s.price,
        s.currency,
        sc.id,
        s.sort_order,
        s.available,
        s.nutrition,
        s.serves_people_min,
        s.serves_people_max,
        NOW(),
        NOW(),
        FALSE
    FROM seed s
    JOIN tbl_sub_category sc ON sc.slug = s.sub_slug AND sc.is_deleted = FALSE
    WHERE NOT EXISTS (
        SELECT 1
        FROM tbl_menu_products p
        WHERE p.menu_id = 4
          AND p.is_deleted = FALSE
          AND LOWER(p.name) = LOWER(s.name)
    )
    RETURNING product_id, name
)
INSERT INTO tbl_menu_product_tag (product_id, tag_id)
SELECT i.product_id, t.id
FROM ins i
JOIN seed s ON LOWER(s.name) = LOWER(i.name)
JOIN LATERAL unnest(s.tag_slugs) AS tag_slug ON TRUE
JOIN tbl_menu_tag t ON t.slug = tag_slug AND t.is_deleted = FALSE
ON CONFLICT (product_id, tag_id) DO NOTHING;
