package com.ael.algoryqrservice.model.enums;

public enum PurchaseLogAction {
    PURCHASE_STARTED,
    PURCHASE_PAYMENT_PENDING,
    PURCHASE_COMPLETED,
    PURCHASE_PAYMENT_FAILED,
    PURCHASE_EXPIRED,
    PURCHASE_CANCELLED,
    ENTITLEMENT_GRANTED,
    ENTITLEMENT_CONSUMED
}
