package com.ael.algoryqrservice.store.model;

public enum StoreOrderStatus {
    PENDING,
    CONFIRMED,
    PREPARING,
    READY,
    ON_THE_WAY,
    DELIVERED,
    REJECTED,
    CANCELLED,
    KITCHEN_PREPARING,
    KITCHEN_PREPARED,
    KITCHEN_DELIVERED_TO_WAITER,
    KITCHEN_DELIVERED_TO_COURIER,
    WAITER_TAKEN,
    COURIER_TAKEN,
    WAITER_DELIVERED_TO_CUSTOMER,
    WAITER_DELIVERED_TO_COURIER,
    COURIER_DELIVERED_TO_CUSTOMER
}
